[package]
name = "asnu_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "asnu_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
ndarray = "0.16"
rand = "0.8"
